### ISSUE TITLE
No configuration item in settings window in PyCharm 5.0.1

### ISSUE THREAD

**Issue by emcek** [ritesh-kapoor/review-board-idea-plugin#12]
There is no way to configure plugin in pycharm 5.0.1, if I search for 'review' in settings window I see only plugin itself
![image](https://cloud.githubusercontent.com/assets/475312/11817692/5cdfec3c-a356-11e5-96ff-5a3ea12813d9.png)

**Comment by emcek** [comment]
Plug icon next to plugin name is grayed-out, so plugin wasn't activated or so...

**Comment by ritesh-kapoor** [comment]
@emcek  Can you please lookup for "Other Settings" in left panel and can you find any "Review board" settings option there? (instead of search)

**Comment by emcek** [comment]
@ritesh-kapoor I've check it before, there is nothing regarding 'review board'

**Comment by ritesh-kapoor** [comment]
can you please download and check wheather you are able to view settings after installing.
https://github.com/ritesh-kapoor/review-board-idea-plugin/releases/download/v0.1.2-beta.1/review-board-idea-plugin.jar

**Comment by emcek** [comment]
with this beta I see Other Settings / Review Board in PyCharm 5.0.2 and 5.0.3 as well
