### ISSUE TITLE
While viewing diff receiving ("You are not logged in", "code": 103) from server

### ISSUE THREAD

**Issue by ritesh-kapoor** [ritesh-kapoor/review-board-idea-plugin#14]

**Comment by ritesh-kapoor** [comment]
@uekemp can you please download and check wheather you are able to view diff after installing.
https://github.com/ritesh-kapoor/review-board-idea-plugin/releases/download/v0.1.2-beta.1/review-board-idea-plugin.jar

Thank you for your support

**Comment by uekemp** [comment]
Yes, works like a charm! I've tested with AS Preview 3b and 4, both do work.

One question: are you planning to allow adding of review comments and issues from within the plugin?

Thanks!

Uli

**Comment by ritesh-kapoor** [comment]
@uekemp Thanks alot for confirming. Adding and viewing comments is already supported in plugin.
