### ISSUE TITLE
Add support for Mercurial

### ISSUE THREAD

**Issue by skewpar** [ritesh-kapoor/review-board-idea-plugin#22]
We use mercurial for our VCS, would like to see support for this to be able to use review board through the IDE.

**Comment by ritesh-kapoor** [comment]
Could you please go to reviewboard settings-> enable rbtools option->Install rbtools latest version->then try to publish

**Comment by skewpar** [comment]
10:40:49 AM ReviewBoard: Cannot run program "rbt" (in directory "C:\Development\WS\project"): CreateProcess error=2, The system cannot find the file specified

Any ideas? I'm able to run rbt from the cmd line in the directory (it's in my PATH variable)

**Comment by waqarkhan88** [comment]
skewpar: i am having same issue.

**Comment by ritesh-kapoor** [comment]
Could you please confirm if the issue is fixed in new build (https://github.com/ritesh-kapoor/review-board-idea-plugin/releases/tag/v0.1.3-beta.1)

**Comment by ritesh-kapoor** [comment]
Closing as per #26
