### ISSUE TITLE
When making a comment, provide a checkbox to create an issue

### ISSUE THREAD

**Issue by bissont** [ritesh-kapoor/review-board-idea-plugin#24]
It seems like right now you can't create a "issue" when adding a new comment. That would be a useful option.

**Comment by ritesh-kapoor** [comment]
#21 is similar issue :)

Also please confirm if the issue is fixed in new build (https://github.com/ritesh-kapoor/review-board-idea-plugin/releases/tag/v0.1.3-beta.1)
