### ISSUE TITLE
Plugin stores ReviewBoard password in clear text

### ISSUE THREAD

**Issue by gershnik-smartsheet** [ritesh-kapoor/review-board-idea-plugin#42]
Not even obfuscated. Inside each source three containing an IntelliJ project.

Note that if user's ReviewBoard server is configured to use LDAP authentication then what the plugin stores is not "just"  ReviewBoard passwords but likely your users domain passwords.

This is simply unacceptable security practice in 2017

**Comment by ritesh-kapoor** [comment]
Review board will not store passwords in plain text now
