### ISSUE TITLE
error when trying to use plugin or trying to test connection

### ISSUE THREAD

**Issue by meran** [ritesh-kapoor/review-board-idea-plugin#6]
Hello,
getting error java.lang.IllegalStateException: Expected BEGIN_OBJECT but was String at line 1 column 1 path $

**Comment by jlchoike** [comment]
I am having the same problem when connecting to ReviewBoard version: 2.5.1.1 (Bitnami Windows installation package).

**Comment by ritesh-kapoor** [comment]
Thanks @meran for you active support in resolving issues
