### ISSUE TITLE
Can't view diffs

### ISSUE THREAD

**Issue by uekemp** [ritesh-kapoor/review-board-idea-plugin#8]
Really a plugin we have been waiting for long! Currently I can see all review requests in the plugin and I can see which changed files a review contains. But I can't see a diff between old and new file version. Neither double click not Crtl-D or right click on a file in the list do work. I have installed Android Studio 1.5 and plugin version 0.1.1

Cheers

**Comment by ritesh-kapoor** [comment]
@uekemp Could you please attach any error information (if any) from events log.

**Comment by uekemp** [comment]
Thanks for the quick response, but neither in file idea.log nor in the Event Log view are any messages related to your plugin. I could raise the log level of IDEA if you would tell me the relevant log categories, if there are any?

**Comment by ritesh-kapoor** [comment]
Could you please provide the JRE, Android Studio build no. As I have tested with Android Studio 1.5 (AI-141.2422023, build on Nov-12-2015) and I'm able to view diffs

**Comment by uekemp** [comment]
Yes, sure. I am working with this configuration:
Build #AI-141.2422023
JRE 1.8.0_60-b27 amd64
Review Board v2.5.1.1

**Comment by ritesh-kapoor** [comment]
Plugin seems to work fine while testing with below configuration
JRE 1.8_66-b17 amd64
AI 141.2422023
Please revert if I could be of any help

**Comment by uekemp** [comment]
After I upgraded to AI 143.2479369 I can now open the diff viewer for files from the review board panel, but if the diff viewer is opened, I get this error message in both sides of the diff: 

{"stat": "fail", "err": {"msg": "You are not logged in", "code": 103}}

But I am logged in, otherwise I couldn't see the file listings.

Cheers

Uli

**Comment by ritesh-kapoor** [comment]
This message is received from reviewboard server. can you test plugin with demo server http://demo.reviewboard.org/. and check if issue persists. Thanks :)

**Comment by ritesh-kapoor** [comment]
Closing this issue for now

**Comment by uekemp** [comment]
Sorry, but I wasn't aware that the plugin is only meant to work with the review board demo server, what a pitty...

**Comment by ritesh-kapoor** [comment]
Firstly, Comment I posted regarding demo server was to just check whether the problem you are facing at your end is only with your reviewboard server or demo server as well. This was to dwell more in the issue to resolve it. Secondly this issues is closed because the reason you raised this issue was because of JDK and which later led to another issue( raising another issue which is helpful to track). I trying my level best to keep plugin uptodate and same thing I expect from contributors as well. Please help to resolve issues rather than giving such statements.

**Comment by uekemp** [comment]
My last comment wasn't appropriate, you are absolutely right. Sorry for that!

**Comment by ritesh-kapoor** [comment]
No Issues :) #14  is opened and will be fixed in next release.
